sources:
  - type: channel
    id: UCevUmOfLTUX9MNGJQKsPdIA      # NeetCodeIO channel id
    include_keywords: ["leetcode", "two pointers", "heap", "dp"]  # filters
    exclude_keywords: ["sponsor", "announcement"]                 # optional
  - type: playlist
    name: Easy problems
    id: PLQpVsaqBj4RIJdYW6Y-iAswxCZeocfoRW
  - type: playlist
    name: Medium problems
    id: PLQpVsaqBj4RLwXMZ9LaAFf4rVowiC3ZcG
  - type: playlist
    name: Hard problems
    id: PLQpVsaqBj4RI3jgIzqK7VJHy8Esacg-ow
  # - type: video               # for specific videos 
  #   id: dQw4w9WgXcQ

limits:
  min_duration_sec: 60
  max_duration_sec: 7200
formats:
  video: "bestvideo+bestaudio/best"
  captions_langs: ["en", "en-US", "en-GB"]
